# Generated by Django 5.0.4 on 2024-05-09 03:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
        ('transacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(blank=True)),
                ('consolidada', models.BooleanField(default=False)),
                ('programada', models.BooleanField(default=False)),
                ('data_programada', models.DateField(blank=True, null=True)),
                ('recorrencia', models.PositiveIntegerField(default=0)),
                ('pago', models.BooleanField(default=False)),
                ('atrasado', models.BooleanField(default=False)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.contabancaria')),
            ],
        ),
    ]
