# Generated by Django 5.0.4 on 2024-05-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='programada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
